### ISSUE TITLE
Interaction with BigInt proposal

### ISSUE THREAD

**Issue by k4b7** [tc39/proposal-extended-numeric-literals#18]
Would `const a = 9007199254740991n_px` be allow?

**Comment by littledan** [comment]
Not in the current proposal. The `n` is a bit redundant, in my opinion. Do you think it should be permitted?

**Comment by k4b7** [comment]
If the `n` is redundant does that mean `_px` stores the number internally as a BigInt?

**Comment by littledan** [comment]
No, it passes both a String and Number representation to _px

**Comment by k4b7** [comment]
So `9007199254740991_px` would result in an object with a truncated `.number` field, but the `.string` field would be `9007199254740991`.

**Comment by michaelficarra** [comment]
@kevinbarabash These functions can do anything. They don't simply return their argument. One thing it may do is parse the `string` given to it as a BigInt and return that.

**Comment by k4b7** [comment]
I see... an object with `.string` and `.number` is passed to `_px` but `_px` could return anything.  Thanks for helping me understand.

**Comment by littledan** [comment]
OK, seems like the question has been answered, so closing the issue.

**Comment by concavelenz** [comment]
I curious why it wouldn't just pass the string what is the point in passing
the number?

**Comment by michaelficarra** [comment]
Probably just convenience since most uses would probably just pass the string to `parseInt` anyway.

**Comment by littledan** [comment]
Performance, to avoid reparsing in the common case. (You can cache on the object with a WeakMap, but this has its own performance cost.)
